// Generated by gencpp from file jarvis_msgs/CleanRes.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_CLEANRES_H
#define JARVIS_MSGS_MESSAGE_CLEANRES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct CleanRes_
{
  typedef CleanRes_<ContainerAllocator> Type;

  CleanRes_()
    : workstation_connect(0)
    , clean_warn(0)
    , clear_water_volume(0)
    , sewage_water_volume(0)
    , clean_mode(0)
    , need_water_sewage(0)
    , squeeegee_dust_mop_stats(0)  {
    }
  CleanRes_(const ContainerAllocator& _alloc)
    : workstation_connect(0)
    , clean_warn(0)
    , clear_water_volume(0)
    , sewage_water_volume(0)
    , clean_mode(0)
    , need_water_sewage(0)
    , squeeegee_dust_mop_stats(0)  {
  (void)_alloc;
    }



   typedef int8_t _workstation_connect_type;
  _workstation_connect_type workstation_connect;

   typedef int8_t _clean_warn_type;
  _clean_warn_type clean_warn;

   typedef int8_t _clear_water_volume_type;
  _clear_water_volume_type clear_water_volume;

   typedef int8_t _sewage_water_volume_type;
  _sewage_water_volume_type sewage_water_volume;

   typedef int8_t _clean_mode_type;
  _clean_mode_type clean_mode;

   typedef int8_t _need_water_sewage_type;
  _need_water_sewage_type need_water_sewage;

   typedef int8_t _squeeegee_dust_mop_stats_type;
  _squeeegee_dust_mop_stats_type squeeegee_dust_mop_stats;





  typedef boost::shared_ptr< ::jarvis_msgs::CleanRes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::CleanRes_<ContainerAllocator> const> ConstPtr;

}; // struct CleanRes_

typedef ::jarvis_msgs::CleanRes_<std::allocator<void> > CleanRes;

typedef boost::shared_ptr< ::jarvis_msgs::CleanRes > CleanResPtr;
typedef boost::shared_ptr< ::jarvis_msgs::CleanRes const> CleanResConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::CleanRes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::CleanRes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::CleanRes_<ContainerAllocator1> & lhs, const ::jarvis_msgs::CleanRes_<ContainerAllocator2> & rhs)
{
  return lhs.workstation_connect == rhs.workstation_connect &&
    lhs.clean_warn == rhs.clean_warn &&
    lhs.clear_water_volume == rhs.clear_water_volume &&
    lhs.sewage_water_volume == rhs.sewage_water_volume &&
    lhs.clean_mode == rhs.clean_mode &&
    lhs.need_water_sewage == rhs.need_water_sewage &&
    lhs.squeeegee_dust_mop_stats == rhs.squeeegee_dust_mop_stats;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::CleanRes_<ContainerAllocator1> & lhs, const ::jarvis_msgs::CleanRes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::CleanRes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::CleanRes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::CleanRes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::CleanRes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::CleanRes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::CleanRes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::CleanRes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0b97e2f90ecf37c858a4e5b459f2f0f";
  }

  static const char* value(const ::jarvis_msgs::CleanRes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0b97e2f90ecf37cULL;
  static const uint64_t static_value2 = 0x858a4e5b459f2f0fULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::CleanRes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/CleanRes";
  }

  static const char* value(const ::jarvis_msgs::CleanRes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::CleanRes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 workstation_connect\n"
"int8 clean_warn\n"
"int8 clear_water_volume\n"
"int8 sewage_water_volume\n"
"int8 clean_mode\n"
"int8 need_water_sewage\n"
"int8 squeeegee_dust_mop_stats\n"
"\n"
;
  }

  static const char* value(const ::jarvis_msgs::CleanRes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::CleanRes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.workstation_connect);
      stream.next(m.clean_warn);
      stream.next(m.clear_water_volume);
      stream.next(m.sewage_water_volume);
      stream.next(m.clean_mode);
      stream.next(m.need_water_sewage);
      stream.next(m.squeeegee_dust_mop_stats);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CleanRes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::CleanRes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::CleanRes_<ContainerAllocator>& v)
  {
    s << indent << "workstation_connect: ";
    Printer<int8_t>::stream(s, indent + "  ", v.workstation_connect);
    s << indent << "clean_warn: ";
    Printer<int8_t>::stream(s, indent + "  ", v.clean_warn);
    s << indent << "clear_water_volume: ";
    Printer<int8_t>::stream(s, indent + "  ", v.clear_water_volume);
    s << indent << "sewage_water_volume: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sewage_water_volume);
    s << indent << "clean_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.clean_mode);
    s << indent << "need_water_sewage: ";
    Printer<int8_t>::stream(s, indent + "  ", v.need_water_sewage);
    s << indent << "squeeegee_dust_mop_stats: ";
    Printer<int8_t>::stream(s, indent + "  ", v.squeeegee_dust_mop_stats);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_CLEANRES_H
