// Generated by gencpp from file jarvis_msgs/Clearance.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_CLEARANCE_H
#define JARVIS_MSGS_MESSAGE_CLEARANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Clearance_
{
  typedef Clearance_<ContainerAllocator> Type;

  Clearance_()
    : stamp()
    , v_slow(0)
    , v_fast(0)
    , front_min(0)
    , front_max(0)
    , side_min(0)
    , side_max(0)
    , rear_min(0)
    , rear_max(0)
    , front(0)
    , rear(0)
    , side(0)  {
    }
  Clearance_(const ContainerAllocator& _alloc)
    : stamp()
    , v_slow(0)
    , v_fast(0)
    , front_min(0)
    , front_max(0)
    , side_min(0)
    , side_max(0)
    , rear_min(0)
    , rear_max(0)
    , front(0)
    , rear(0)
    , side(0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int32_t _v_slow_type;
  _v_slow_type v_slow;

   typedef int32_t _v_fast_type;
  _v_fast_type v_fast;

   typedef int32_t _front_min_type;
  _front_min_type front_min;

   typedef int32_t _front_max_type;
  _front_max_type front_max;

   typedef int32_t _side_min_type;
  _side_min_type side_min;

   typedef int32_t _side_max_type;
  _side_max_type side_max;

   typedef int32_t _rear_min_type;
  _rear_min_type rear_min;

   typedef int32_t _rear_max_type;
  _rear_max_type rear_max;

   typedef int32_t _front_type;
  _front_type front;

   typedef int32_t _rear_type;
  _rear_type rear;

   typedef int32_t _side_type;
  _side_type side;





  typedef boost::shared_ptr< ::jarvis_msgs::Clearance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Clearance_<ContainerAllocator> const> ConstPtr;

}; // struct Clearance_

typedef ::jarvis_msgs::Clearance_<std::allocator<void> > Clearance;

typedef boost::shared_ptr< ::jarvis_msgs::Clearance > ClearancePtr;
typedef boost::shared_ptr< ::jarvis_msgs::Clearance const> ClearanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Clearance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Clearance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Clearance_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Clearance_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.v_slow == rhs.v_slow &&
    lhs.v_fast == rhs.v_fast &&
    lhs.front_min == rhs.front_min &&
    lhs.front_max == rhs.front_max &&
    lhs.side_min == rhs.side_min &&
    lhs.side_max == rhs.side_max &&
    lhs.rear_min == rhs.rear_min &&
    lhs.rear_max == rhs.rear_max &&
    lhs.front == rhs.front &&
    lhs.rear == rhs.rear &&
    lhs.side == rhs.side;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Clearance_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Clearance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Clearance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Clearance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Clearance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Clearance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Clearance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Clearance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Clearance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef2282c6031d6ba94ac61da6dd5629f6";
  }

  static const char* value(const ::jarvis_msgs::Clearance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef2282c6031d6ba9ULL;
  static const uint64_t static_value2 = 0x4ac61da6dd5629f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Clearance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Clearance";
  }

  static const char* value(const ::jarvis_msgs::Clearance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Clearance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"int32 v_slow\n"
"int32 v_fast\n"
"int32 front_min\n"
"int32 front_max\n"
"int32 side_min\n"
"int32 side_max\n"
"int32 rear_min\n"
"int32 rear_max\n"
"int32 front\n"
"int32 rear\n"
"int32 side\n"
"\n"
;
  }

  static const char* value(const ::jarvis_msgs::Clearance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Clearance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.v_slow);
      stream.next(m.v_fast);
      stream.next(m.front_min);
      stream.next(m.front_max);
      stream.next(m.side_min);
      stream.next(m.side_max);
      stream.next(m.rear_min);
      stream.next(m.rear_max);
      stream.next(m.front);
      stream.next(m.rear);
      stream.next(m.side);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Clearance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Clearance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Clearance_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "v_slow: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v_slow);
    s << indent << "v_fast: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v_fast);
    s << indent << "front_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.front_min);
    s << indent << "front_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.front_max);
    s << indent << "side_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.side_min);
    s << indent << "side_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.side_max);
    s << indent << "rear_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rear_min);
    s << indent << "rear_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rear_max);
    s << indent << "front: ";
    Printer<int32_t>::stream(s, indent + "  ", v.front);
    s << indent << "rear: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rear);
    s << indent << "side: ";
    Printer<int32_t>::stream(s, indent + "  ", v.side);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_CLEARANCE_H
