// Generated by gencpp from file jarvis_msgs/Cmd.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_CMD_H
#define JARVIS_MSGS_MESSAGE_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jarvis_msgs/CmdData.h>

namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Cmd_
{
  typedef Cmd_<ContainerAllocator> Type;

  Cmd_()
    : cmd(0)
    , data()  {
    }
  Cmd_(const ContainerAllocator& _alloc)
    : cmd(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _cmd_type;
  _cmd_type cmd;

   typedef  ::jarvis_msgs::CmdData_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::jarvis_msgs::Cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Cmd_<ContainerAllocator> const> ConstPtr;

}; // struct Cmd_

typedef ::jarvis_msgs::Cmd_<std::allocator<void> > Cmd;

typedef boost::shared_ptr< ::jarvis_msgs::Cmd > CmdPtr;
typedef boost::shared_ptr< ::jarvis_msgs::Cmd const> CmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Cmd_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Cmd_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Cmd_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1772cc73029ce4f28d14f39733a491b3";
  }

  static const char* value(const ::jarvis_msgs::Cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1772cc73029ce4f2ULL;
  static const uint64_t static_value2 = 0x8d14f39733a491b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Cmd";
  }

  static const char* value(const ::jarvis_msgs::Cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 cmd\n"
"CmdData data\n"
"\n"
"================================================================================\n"
"MSG: jarvis_msgs/CmdData\n"
"int8 arg_int8\n"
"int32 arg_int32\n"
"string arg_str\n"
;
  }

  static const char* value(const ::jarvis_msgs::Cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Cmd_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::jarvis_msgs::CmdData_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_CMD_H
