// Generated by gencpp from file jarvis_msgs/CmdData.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_CMDDATA_H
#define JARVIS_MSGS_MESSAGE_CMDDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct CmdData_
{
  typedef CmdData_<ContainerAllocator> Type;

  CmdData_()
    : arg_int8(0)
    , arg_int32(0)
    , arg_str()  {
    }
  CmdData_(const ContainerAllocator& _alloc)
    : arg_int8(0)
    , arg_int32(0)
    , arg_str(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _arg_int8_type;
  _arg_int8_type arg_int8;

   typedef int32_t _arg_int32_type;
  _arg_int32_type arg_int32;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _arg_str_type;
  _arg_str_type arg_str;





  typedef boost::shared_ptr< ::jarvis_msgs::CmdData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::CmdData_<ContainerAllocator> const> ConstPtr;

}; // struct CmdData_

typedef ::jarvis_msgs::CmdData_<std::allocator<void> > CmdData;

typedef boost::shared_ptr< ::jarvis_msgs::CmdData > CmdDataPtr;
typedef boost::shared_ptr< ::jarvis_msgs::CmdData const> CmdDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::CmdData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::CmdData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::CmdData_<ContainerAllocator1> & lhs, const ::jarvis_msgs::CmdData_<ContainerAllocator2> & rhs)
{
  return lhs.arg_int8 == rhs.arg_int8 &&
    lhs.arg_int32 == rhs.arg_int32 &&
    lhs.arg_str == rhs.arg_str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::CmdData_<ContainerAllocator1> & lhs, const ::jarvis_msgs::CmdData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::CmdData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::CmdData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::CmdData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::CmdData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::CmdData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::CmdData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::CmdData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4004813211334f3c0d8970d1d0786679";
  }

  static const char* value(const ::jarvis_msgs::CmdData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4004813211334f3cULL;
  static const uint64_t static_value2 = 0x0d8970d1d0786679ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::CmdData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/CmdData";
  }

  static const char* value(const ::jarvis_msgs::CmdData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::CmdData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 arg_int8\n"
"int32 arg_int32\n"
"string arg_str\n"
;
  }

  static const char* value(const ::jarvis_msgs::CmdData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::CmdData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arg_int8);
      stream.next(m.arg_int32);
      stream.next(m.arg_str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CmdData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::CmdData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::CmdData_<ContainerAllocator>& v)
  {
    s << indent << "arg_int8: ";
    Printer<int8_t>::stream(s, indent + "  ", v.arg_int8);
    s << indent << "arg_int32: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arg_int32);
    s << indent << "arg_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.arg_str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_CMDDATA_H
