// Generated by gencpp from file jarvis_msgs/Fault.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_FAULT_H
#define JARVIS_MSGS_MESSAGE_FAULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Fault_
{
  typedef Fault_<ContainerAllocator> Type;

  Fault_()
    : system(0)
    , driver(0)  {
    }
  Fault_(const ContainerAllocator& _alloc)
    : system(0)
    , driver(0)  {
  (void)_alloc;
    }



   typedef int16_t _system_type;
  _system_type system;

   typedef int32_t _driver_type;
  _driver_type driver;





  typedef boost::shared_ptr< ::jarvis_msgs::Fault_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Fault_<ContainerAllocator> const> ConstPtr;

}; // struct Fault_

typedef ::jarvis_msgs::Fault_<std::allocator<void> > Fault;

typedef boost::shared_ptr< ::jarvis_msgs::Fault > FaultPtr;
typedef boost::shared_ptr< ::jarvis_msgs::Fault const> FaultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Fault_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Fault_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Fault_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Fault_<ContainerAllocator2> & rhs)
{
  return lhs.system == rhs.system &&
    lhs.driver == rhs.driver;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Fault_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Fault_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Fault_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Fault_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Fault_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Fault_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Fault_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Fault_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Fault_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47f590810136b4cba111d5af25c2628e";
  }

  static const char* value(const ::jarvis_msgs::Fault_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47f590810136b4cbULL;
  static const uint64_t static_value2 = 0xa111d5af25c2628eULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Fault_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Fault";
  }

  static const char* value(const ::jarvis_msgs::Fault_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Fault_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 system\n"
"int32 driver\n"
"\n"
;
  }

  static const char* value(const ::jarvis_msgs::Fault_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Fault_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.system);
      stream.next(m.driver);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Fault_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Fault_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Fault_<ContainerAllocator>& v)
  {
    s << indent << "system: ";
    Printer<int16_t>::stream(s, indent + "  ", v.system);
    s << indent << "driver: ";
    Printer<int32_t>::stream(s, indent + "  ", v.driver);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_FAULT_H
