// Generated by gencpp from file jarvis_msgs/FollowVelAck.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_FOLLOWVELACK_H
#define JARVIS_MSGS_MESSAGE_FOLLOWVELACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jarvis_msgs/VelAckerman.h>

namespace jarvis_msgs
{
template <class ContainerAllocator>
struct FollowVelAck_
{
  typedef FollowVelAck_<ContainerAllocator> Type;

  FollowVelAck_()
    : stamp()
    , state(0)
    , VelAck()  {
    }
  FollowVelAck_(const ContainerAllocator& _alloc)
    : stamp()
    , state(0)
    , VelAck(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int8_t _state_type;
  _state_type state;

   typedef  ::jarvis_msgs::VelAckerman_<ContainerAllocator>  _VelAck_type;
  _VelAck_type VelAck;





  typedef boost::shared_ptr< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> const> ConstPtr;

}; // struct FollowVelAck_

typedef ::jarvis_msgs::FollowVelAck_<std::allocator<void> > FollowVelAck;

typedef boost::shared_ptr< ::jarvis_msgs::FollowVelAck > FollowVelAckPtr;
typedef boost::shared_ptr< ::jarvis_msgs::FollowVelAck const> FollowVelAckConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::FollowVelAck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::FollowVelAck_<ContainerAllocator1> & lhs, const ::jarvis_msgs::FollowVelAck_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.state == rhs.state &&
    lhs.VelAck == rhs.VelAck;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::FollowVelAck_<ContainerAllocator1> & lhs, const ::jarvis_msgs::FollowVelAck_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46bb78bee8f9b519df6c82119e4b785f";
  }

  static const char* value(const ::jarvis_msgs::FollowVelAck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46bb78bee8f9b519ULL;
  static const uint64_t static_value2 = 0xdf6c82119e4b785fULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/FollowVelAck";
  }

  static const char* value(const ::jarvis_msgs::FollowVelAck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"int8 state\n"
"jarvis_msgs/VelAckerman VelAck\n"
"\n"
"================================================================================\n"
"MSG: jarvis_msgs/VelAckerman\n"
"uint32 stamp\n"
"float32 angle_front\n"
"float32 angle_back\n"
"float32 v_fleft\n"
"float32 v_fright\n"
"float32 v_bleft\n"
"float32 v_bright\n"
;
  }

  static const char* value(const ::jarvis_msgs::FollowVelAck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.state);
      stream.next(m.VelAck);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowVelAck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::FollowVelAck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::FollowVelAck_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "VelAck: ";
    s << std::endl;
    Printer< ::jarvis_msgs::VelAckerman_<ContainerAllocator> >::stream(s, indent + "  ", v.VelAck);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_FOLLOWVELACK_H
