// Generated by gencpp from file jarvis_msgs/FollowVel.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_FOLLOWVEL_H
#define JARVIS_MSGS_MESSAGE_FOLLOWVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace jarvis_msgs
{
template <class ContainerAllocator>
struct FollowVel_
{
  typedef FollowVel_<ContainerAllocator> Type;

  FollowVel_()
    : stamp()
    , state(0)
    , vel()  {
    }
  FollowVel_(const ContainerAllocator& _alloc)
    : stamp()
    , state(0)
    , vel(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int8_t _state_type;
  _state_type state;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::jarvis_msgs::FollowVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::FollowVel_<ContainerAllocator> const> ConstPtr;

}; // struct FollowVel_

typedef ::jarvis_msgs::FollowVel_<std::allocator<void> > FollowVel;

typedef boost::shared_ptr< ::jarvis_msgs::FollowVel > FollowVelPtr;
typedef boost::shared_ptr< ::jarvis_msgs::FollowVel const> FollowVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::FollowVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::FollowVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::FollowVel_<ContainerAllocator1> & lhs, const ::jarvis_msgs::FollowVel_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.state == rhs.state &&
    lhs.vel == rhs.vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::FollowVel_<ContainerAllocator1> & lhs, const ::jarvis_msgs::FollowVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::FollowVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::FollowVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::FollowVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::FollowVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::FollowVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::FollowVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::FollowVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac88e2cf60fdc1ce823758ab9bad37ff";
  }

  static const char* value(const ::jarvis_msgs::FollowVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac88e2cf60fdc1ceULL;
  static const uint64_t static_value2 = 0x823758ab9bad37ffULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::FollowVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/FollowVel";
  }

  static const char* value(const ::jarvis_msgs::FollowVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::FollowVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"int8 state\n"
"geometry_msgs/Twist vel\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::jarvis_msgs::FollowVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::FollowVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.state);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::FollowVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::FollowVel_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_FOLLOWVEL_H
