// Generated by gencpp from file jarvis_msgs/GetTagId.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_GETTAGID_H
#define JARVIS_MSGS_MESSAGE_GETTAGID_H

#include <ros/service_traits.h>


#include <jarvis_msgs/GetTagIdRequest.h>
#include <jarvis_msgs/GetTagIdResponse.h>


namespace jarvis_msgs
{

struct GetTagId
{

typedef GetTagIdRequest Request;
typedef GetTagIdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTagId
} // namespace jarvis_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jarvis_msgs::GetTagId > {
  static const char* value()
  {
    return "7fa0fec2aa0e7baae28e7c158196a79b";
  }

  static const char* value(const ::jarvis_msgs::GetTagId&) { return value(); }
};

template<>
struct DataType< ::jarvis_msgs::GetTagId > {
  static const char* value()
  {
    return "jarvis_msgs/GetTagId";
  }

  static const char* value(const ::jarvis_msgs::GetTagId&) { return value(); }
};


// service_traits::MD5Sum< ::jarvis_msgs::GetTagIdRequest> should match
// service_traits::MD5Sum< ::jarvis_msgs::GetTagId >
template<>
struct MD5Sum< ::jarvis_msgs::GetTagIdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jarvis_msgs::GetTagId >::value();
  }
  static const char* value(const ::jarvis_msgs::GetTagIdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jarvis_msgs::GetTagIdRequest> should match
// service_traits::DataType< ::jarvis_msgs::GetTagId >
template<>
struct DataType< ::jarvis_msgs::GetTagIdRequest>
{
  static const char* value()
  {
    return DataType< ::jarvis_msgs::GetTagId >::value();
  }
  static const char* value(const ::jarvis_msgs::GetTagIdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jarvis_msgs::GetTagIdResponse> should match
// service_traits::MD5Sum< ::jarvis_msgs::GetTagId >
template<>
struct MD5Sum< ::jarvis_msgs::GetTagIdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jarvis_msgs::GetTagId >::value();
  }
  static const char* value(const ::jarvis_msgs::GetTagIdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jarvis_msgs::GetTagIdResponse> should match
// service_traits::DataType< ::jarvis_msgs::GetTagId >
template<>
struct DataType< ::jarvis_msgs::GetTagIdResponse>
{
  static const char* value()
  {
    return DataType< ::jarvis_msgs::GetTagId >::value();
  }
  static const char* value(const ::jarvis_msgs::GetTagIdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_GETTAGID_H
