// Generated by gencpp from file jarvis_msgs/GetTagIdRequest.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_GETTAGIDREQUEST_H
#define JARVIS_MSGS_MESSAGE_GETTAGIDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct GetTagIdRequest_
{
  typedef GetTagIdRequest_<ContainerAllocator> Type;

  GetTagIdRequest_()
    : cam_name()  {
    }
  GetTagIdRequest_(const ContainerAllocator& _alloc)
    : cam_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cam_name_type;
  _cam_name_type cam_name;





  typedef boost::shared_ptr< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTagIdRequest_

typedef ::jarvis_msgs::GetTagIdRequest_<std::allocator<void> > GetTagIdRequest;

typedef boost::shared_ptr< ::jarvis_msgs::GetTagIdRequest > GetTagIdRequestPtr;
typedef boost::shared_ptr< ::jarvis_msgs::GetTagIdRequest const> GetTagIdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator1> & lhs, const ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cam_name == rhs.cam_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator1> & lhs, const ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a25abf38155a79064325f12ede77e9e";
  }

  static const char* value(const ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a25abf38155a790ULL;
  static const uint64_t static_value2 = 0x64325f12ede77e9eULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/GetTagIdRequest";
  }

  static const char* value(const ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string cam_name\n"
;
  }

  static const char* value(const ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cam_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTagIdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::GetTagIdRequest_<ContainerAllocator>& v)
  {
    s << indent << "cam_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cam_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_GETTAGIDREQUEST_H
