// Generated by gencpp from file jarvis_msgs/GetTagIdResponse.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_GETTAGIDRESPONSE_H
#define JARVIS_MSGS_MESSAGE_GETTAGIDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct GetTagIdResponse_
{
  typedef GetTagIdResponse_<ContainerAllocator> Type;

  GetTagIdResponse_()
    : tag_id()  {
    }
  GetTagIdResponse_(const ContainerAllocator& _alloc)
    : tag_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _tag_id_type;
  _tag_id_type tag_id;





  typedef boost::shared_ptr< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTagIdResponse_

typedef ::jarvis_msgs::GetTagIdResponse_<std::allocator<void> > GetTagIdResponse;

typedef boost::shared_ptr< ::jarvis_msgs::GetTagIdResponse > GetTagIdResponsePtr;
typedef boost::shared_ptr< ::jarvis_msgs::GetTagIdResponse const> GetTagIdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator1> & lhs, const ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.tag_id == rhs.tag_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator1> & lhs, const ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "613e7204cc46d903ed244360aaa6a0db";
  }

  static const char* value(const ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x613e7204cc46d903ULL;
  static const uint64_t static_value2 = 0xed244360aaa6a0dbULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/GetTagIdResponse";
  }

  static const char* value(const ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tag_id\n"
"\n"
;
  }

  static const char* value(const ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTagIdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::GetTagIdResponse_<ContainerAllocator>& v)
  {
    s << indent << "tag_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tag_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_GETTAGIDRESPONSE_H
