// Generated by gencpp from file jarvis_msgs/Info.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_INFO_H
#define JARVIS_MSGS_MESSAGE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Info_
{
  typedef Info_<ContainerAllocator> Type;

  Info_()
    : input(0)
    , output(0)
    , battery(0)
    , soh(0)
    , distance(0.0)
    , lifter_state(0)
    , rotate_angle(0)  {
    }
  Info_(const ContainerAllocator& _alloc)
    : input(0)
    , output(0)
    , battery(0)
    , soh(0)
    , distance(0.0)
    , lifter_state(0)
    , rotate_angle(0)  {
  (void)_alloc;
    }



   typedef int32_t _input_type;
  _input_type input;

   typedef int32_t _output_type;
  _output_type output;

   typedef int8_t _battery_type;
  _battery_type battery;

   typedef int32_t _soh_type;
  _soh_type soh;

   typedef float _distance_type;
  _distance_type distance;

   typedef int8_t _lifter_state_type;
  _lifter_state_type lifter_state;

   typedef int16_t _rotate_angle_type;
  _rotate_angle_type rotate_angle;





  typedef boost::shared_ptr< ::jarvis_msgs::Info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Info_<ContainerAllocator> const> ConstPtr;

}; // struct Info_

typedef ::jarvis_msgs::Info_<std::allocator<void> > Info;

//typedef ::jarvis_msgs::Vel_<std::allocator<void> > Vel; //

typedef boost::shared_ptr< ::jarvis_msgs::Info > InfoPtr;
typedef boost::shared_ptr< ::jarvis_msgs::Info const> InfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Info_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Info_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input &&
    lhs.output == rhs.output &&
    lhs.battery == rhs.battery &&
    lhs.soh == rhs.soh &&
    lhs.distance == rhs.distance &&
    lhs.lifter_state == rhs.lifter_state &&
    lhs.rotate_angle == rhs.rotate_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Info_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60b61295961aeeaaf02972b53fb7fe03";
  }

  static const char* value(const ::jarvis_msgs::Info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60b61295961aeeaaULL;
  static const uint64_t static_value2 = 0xf02972b53fb7fe03ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Info";
  }

  static const char* value(const ::jarvis_msgs::Info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 input\n"
"int32 output\n"
"int8 battery\n"
"int32 soh\n"
"float32 distance\n"
"int8 lifter_state\n"
"int16 rotate_angle\n"
;
  }

  static const char* value(const ::jarvis_msgs::Info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
      stream.next(m.output);
      stream.next(m.battery);
      stream.next(m.soh);
      stream.next(m.distance);
      stream.next(m.lifter_state);
      stream.next(m.rotate_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Info_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<int32_t>::stream(s, indent + "  ", v.input);
    s << indent << "output: ";
    Printer<int32_t>::stream(s, indent + "  ", v.output);
    s << indent << "battery: ";
    Printer<int8_t>::stream(s, indent + "  ", v.battery);
    s << indent << "soh: ";
    Printer<int32_t>::stream(s, indent + "  ", v.soh);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "lifter_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.lifter_state);
    s << indent << "rotate_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rotate_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_INFO_H
