// Generated by gencpp from file jarvis_msgs/Json.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_JSON_H
#define JARVIS_MSGS_MESSAGE_JSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Json_
{
  typedef Json_<ContainerAllocator> Type;

  Json_()
    : json()  {
    }
  Json_(const ContainerAllocator& _alloc)
    : json(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _json_type;
  _json_type json;





  typedef boost::shared_ptr< ::jarvis_msgs::Json_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Json_<ContainerAllocator> const> ConstPtr;

}; // struct Json_

typedef ::jarvis_msgs::Json_<std::allocator<void> > Json;

typedef boost::shared_ptr< ::jarvis_msgs::Json > JsonPtr;
typedef boost::shared_ptr< ::jarvis_msgs::Json const> JsonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Json_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Json_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Json_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Json_<ContainerAllocator2> & rhs)
{
  return lhs.json == rhs.json;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Json_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Json_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Json_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Json_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Json_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Json_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Json_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Json_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Json_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f859d01b8e3757110b53b06e823ec597";
  }

  static const char* value(const ::jarvis_msgs::Json_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf859d01b8e375711ULL;
  static const uint64_t static_value2 = 0x0b53b06e823ec597ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Json_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Json";
  }

  static const char* value(const ::jarvis_msgs::Json_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Json_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string json\n"
;
  }

  static const char* value(const ::jarvis_msgs::Json_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Json_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Json_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Json_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Json_<ContainerAllocator>& v)
  {
    s << indent << "json: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.json);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_JSON_H
