// Generated by gencpp from file jarvis_msgs/LocInit.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_LOCINIT_H
#define JARVIS_MSGS_MESSAGE_LOCINIT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct LocInit_
{
  typedef LocInit_<ContainerAllocator> Type;

  LocInit_()
    : stamp()
    , x(0.0)
    , y(0.0)
    , t(0.0)  {
    }
  LocInit_(const ContainerAllocator& _alloc)
    : stamp()
    , x(0.0)
    , y(0.0)
    , t(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _t_type;
  _t_type t;





  typedef boost::shared_ptr< ::jarvis_msgs::LocInit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::LocInit_<ContainerAllocator> const> ConstPtr;

}; // struct LocInit_

typedef ::jarvis_msgs::LocInit_<std::allocator<void> > LocInit;

typedef boost::shared_ptr< ::jarvis_msgs::LocInit > LocInitPtr;
typedef boost::shared_ptr< ::jarvis_msgs::LocInit const> LocInitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::LocInit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::LocInit_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::LocInit_<ContainerAllocator1> & lhs, const ::jarvis_msgs::LocInit_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.t == rhs.t;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::LocInit_<ContainerAllocator1> & lhs, const ::jarvis_msgs::LocInit_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::LocInit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::LocInit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::LocInit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::LocInit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::LocInit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::LocInit_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::LocInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36449c56eea7a8593343086fd6482eef";
  }

  static const char* value(const ::jarvis_msgs::LocInit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36449c56eea7a859ULL;
  static const uint64_t static_value2 = 0x3343086fd6482eefULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::LocInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/LocInit";
  }

  static const char* value(const ::jarvis_msgs::LocInit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::LocInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float64 x\n"
"float64 y\n"
"float64 t\n"
;
  }

  static const char* value(const ::jarvis_msgs::LocInit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::LocInit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.t);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocInit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::LocInit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::LocInit_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "t: ";
    Printer<double>::stream(s, indent + "  ", v.t);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_LOCINIT_H
