// Generated by gencpp from file jarvis_msgs/LocResult.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_LOCRESULT_H
#define JARVIS_MSGS_MESSAGE_LOCRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct LocResult_
{
  typedef LocResult_<ContainerAllocator> Type;

  LocResult_()
    : stamp()
    , x(0.0)
    , y(0.0)
    , t(0.0)
    , score(0)
    , state(0)  {
    }
  LocResult_(const ContainerAllocator& _alloc)
    : stamp()
    , x(0.0)
    , y(0.0)
    , t(0.0)
    , score(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _t_type;
  _t_type t;

   typedef int32_t _score_type;
  _score_type score;

   typedef int8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::jarvis_msgs::LocResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::LocResult_<ContainerAllocator> const> ConstPtr;

}; // struct LocResult_

typedef ::jarvis_msgs::LocResult_<std::allocator<void> > LocResult;

typedef boost::shared_ptr< ::jarvis_msgs::LocResult > LocResultPtr;
typedef boost::shared_ptr< ::jarvis_msgs::LocResult const> LocResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::LocResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::LocResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::LocResult_<ContainerAllocator1> & lhs, const ::jarvis_msgs::LocResult_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.t == rhs.t &&
    lhs.score == rhs.score &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::LocResult_<ContainerAllocator1> & lhs, const ::jarvis_msgs::LocResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::LocResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::LocResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::LocResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::LocResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::LocResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::LocResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::LocResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f418e8fcd391b4f87537f31da0158ff5";
  }

  static const char* value(const ::jarvis_msgs::LocResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf418e8fcd391b4f8ULL;
  static const uint64_t static_value2 = 0x7537f31da0158ff5ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::LocResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/LocResult";
  }

  static const char* value(const ::jarvis_msgs::LocResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::LocResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float64 x\n"
"float64 y\n"
"float64 t\n"
"int32 score\n"
"int8 state\n"
;
  }

  static const char* value(const ::jarvis_msgs::LocResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::LocResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.t);
      stream.next(m.score);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::LocResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::LocResult_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "t: ";
    Printer<double>::stream(s, indent + "  ", v.t);
    s << indent << "score: ";
    Printer<int32_t>::stream(s, indent + "  ", v.score);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_LOCRESULT_H
