// Generated by gencpp from file jarvis_msgs/Map.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_MAP_H
#define JARVIS_MSGS_MESSAGE_MAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Map_
{
  typedef Map_<ContainerAllocator> Type;

  Map_()
    : stamp()
    , name()
    , path()  {
    }
  Map_(const ContainerAllocator& _alloc)
    : stamp()
    , name(_alloc)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::jarvis_msgs::Map_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Map_<ContainerAllocator> const> ConstPtr;

}; // struct Map_

typedef ::jarvis_msgs::Map_<std::allocator<void> > Map;

typedef boost::shared_ptr< ::jarvis_msgs::Map > MapPtr;
typedef boost::shared_ptr< ::jarvis_msgs::Map const> MapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Map_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Map_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Map_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Map_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.name == rhs.name &&
    lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Map_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Map_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Map_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Map_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Map_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8c72a9f7a548bf84d4437eb9ed516cc";
  }

  static const char* value(const ::jarvis_msgs::Map_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8c72a9f7a548bf8ULL;
  static const uint64_t static_value2 = 0x4d4437eb9ed516ccULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Map";
  }

  static const char* value(const ::jarvis_msgs::Map_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"string name\n"
"string path\n"
"\n"
;
  }

  static const char* value(const ::jarvis_msgs::Map_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Map_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.name);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Map_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Map_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Map_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_MAP_H
