// Generated by gencpp from file jarvis_msgs/MotorAckerman.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_MOTORACKERMAN_H
#define JARVIS_MSGS_MESSAGE_MOTORACKERMAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct MotorAckerman_
{
  typedef MotorAckerman_<ContainerAllocator> Type;

  MotorAckerman_()
    : stamp(0)
    , angle_front(0.0)
    , angle_back(0.0)
    , v_fleft(0.0)
    , v_fright(0.0)
    , v_bleft(0.0)
    , v_bright(0.0)
    , motor(false)
    , charging(false)  {
    }
  MotorAckerman_(const ContainerAllocator& _alloc)
    : stamp(0)
    , angle_front(0.0)
    , angle_back(0.0)
    , v_fleft(0.0)
    , v_fright(0.0)
    , v_bleft(0.0)
    , v_bright(0.0)
    , motor(false)
    , charging(false)  {
  (void)_alloc;
    }



   typedef uint32_t _stamp_type;
  _stamp_type stamp;

   typedef float _angle_front_type;
  _angle_front_type angle_front;

   typedef float _angle_back_type;
  _angle_back_type angle_back;

   typedef float _v_fleft_type;
  _v_fleft_type v_fleft;

   typedef float _v_fright_type;
  _v_fright_type v_fright;

   typedef float _v_bleft_type;
  _v_bleft_type v_bleft;

   typedef float _v_bright_type;
  _v_bright_type v_bright;

   typedef uint8_t _motor_type;
  _motor_type motor;

   typedef uint8_t _charging_type;
  _charging_type charging;





  typedef boost::shared_ptr< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> const> ConstPtr;

}; // struct MotorAckerman_

typedef ::jarvis_msgs::MotorAckerman_<std::allocator<void> > MotorAckerman;

typedef boost::shared_ptr< ::jarvis_msgs::MotorAckerman > MotorAckermanPtr;
typedef boost::shared_ptr< ::jarvis_msgs::MotorAckerman const> MotorAckermanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::MotorAckerman_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::MotorAckerman_<ContainerAllocator1> & lhs, const ::jarvis_msgs::MotorAckerman_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.angle_front == rhs.angle_front &&
    lhs.angle_back == rhs.angle_back &&
    lhs.v_fleft == rhs.v_fleft &&
    lhs.v_fright == rhs.v_fright &&
    lhs.v_bleft == rhs.v_bleft &&
    lhs.v_bright == rhs.v_bright &&
    lhs.motor == rhs.motor &&
    lhs.charging == rhs.charging;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::MotorAckerman_<ContainerAllocator1> & lhs, const ::jarvis_msgs::MotorAckerman_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> >
{
  static const char* value()
  {
    return "792658e150ddfdd076d87bd728af5367";
  }

  static const char* value(const ::jarvis_msgs::MotorAckerman_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x792658e150ddfdd0ULL;
  static const uint64_t static_value2 = 0x76d87bd728af5367ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/MotorAckerman";
  }

  static const char* value(const ::jarvis_msgs::MotorAckerman_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 stamp\n"
"float32 angle_front\n"
"float32 angle_back\n"
"float32 v_fleft\n"
"float32 v_fright\n"
"float32 v_bleft\n"
"float32 v_bright\n"
"bool motor\n"
"bool charging\n"
;
  }

  static const char* value(const ::jarvis_msgs::MotorAckerman_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.angle_front);
      stream.next(m.angle_back);
      stream.next(m.v_fleft);
      stream.next(m.v_fright);
      stream.next(m.v_bleft);
      stream.next(m.v_bright);
      stream.next(m.motor);
      stream.next(m.charging);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorAckerman_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::MotorAckerman_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::MotorAckerman_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.stamp);
    s << indent << "angle_front: ";
    Printer<float>::stream(s, indent + "  ", v.angle_front);
    s << indent << "angle_back: ";
    Printer<float>::stream(s, indent + "  ", v.angle_back);
    s << indent << "v_fleft: ";
    Printer<float>::stream(s, indent + "  ", v.v_fleft);
    s << indent << "v_fright: ";
    Printer<float>::stream(s, indent + "  ", v.v_fright);
    s << indent << "v_bleft: ";
    Printer<float>::stream(s, indent + "  ", v.v_bleft);
    s << indent << "v_bright: ";
    Printer<float>::stream(s, indent + "  ", v.v_bright);
    s << indent << "motor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor);
    s << indent << "charging: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.charging);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_MOTORACKERMAN_H
