// Generated by gencpp from file jarvis_msgs/Odom.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_ODOM_H
#define JARVIS_MSGS_MESSAGE_ODOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Odom_
{
  typedef Odom_<ContainerAllocator> Type;

  Odom_()
    : stamp(0)
    , x(0.0)
    , y(0.0)
    , t(0.0)
    , v(0.0)
    , w(0.0)
    , motor(false)
    , charging(false)  {
    }
  Odom_(const ContainerAllocator& _alloc)
    : stamp(0)
    , x(0.0)
    , y(0.0)
    , t(0.0)
    , v(0.0)
    , w(0.0)
    , motor(false)
    , charging(false)  {
  (void)_alloc;
    }



   typedef uint32_t _stamp_type;
  _stamp_type stamp;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _t_type;
  _t_type t;

   typedef float _v_type;
  _v_type v;

   typedef float _w_type;
  _w_type w;

   typedef uint8_t _motor_type;
  _motor_type motor;

   typedef uint8_t _charging_type;
  _charging_type charging;





  typedef boost::shared_ptr< ::jarvis_msgs::Odom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Odom_<ContainerAllocator> const> ConstPtr;

}; // struct Odom_

typedef ::jarvis_msgs::Odom_<std::allocator<void> > Odom;

typedef boost::shared_ptr< ::jarvis_msgs::Odom > OdomPtr;
typedef boost::shared_ptr< ::jarvis_msgs::Odom const> OdomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Odom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Odom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Odom_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Odom_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.t == rhs.t &&
    lhs.v == rhs.v &&
    lhs.w == rhs.w &&
    lhs.motor == rhs.motor &&
    lhs.charging == rhs.charging;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Odom_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Odom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Odom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Odom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea7b741f827b24670eeedce58c542b78";
  }

  static const char* value(const ::jarvis_msgs::Odom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea7b741f827b2467ULL;
  static const uint64_t static_value2 = 0x0eeedce58c542b78ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Odom";
  }

  static const char* value(const ::jarvis_msgs::Odom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 stamp\n"
"float32 x\n"
"float32 y\n"
"float32 t\n"
"float32 v\n"
"float32 w\n"
"bool motor\n"
"bool charging\n"
;
  }

  static const char* value(const ::jarvis_msgs::Odom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Odom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.t);
      stream.next(m.v);
      stream.next(m.w);
      stream.next(m.motor);
      stream.next(m.charging);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Odom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Odom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Odom_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.stamp);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "t: ";
    Printer<float>::stream(s, indent + "  ", v.t);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    s << indent << "motor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor);
    s << indent << "charging: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.charging);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_ODOM_H
