// Generated by gencpp from file jarvis_msgs/Param.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_PARAM_H
#define JARVIS_MSGS_MESSAGE_PARAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Param_
{
  typedef Param_<ContainerAllocator> Type;

  Param_()
    : stamp()
    , sections()  {
    }
  Param_(const ContainerAllocator& _alloc)
    : stamp()
    , sections(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sections_type;
  _sections_type sections;





  typedef boost::shared_ptr< ::jarvis_msgs::Param_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Param_<ContainerAllocator> const> ConstPtr;

}; // struct Param_

typedef ::jarvis_msgs::Param_<std::allocator<void> > Param;

typedef boost::shared_ptr< ::jarvis_msgs::Param > ParamPtr;
typedef boost::shared_ptr< ::jarvis_msgs::Param const> ParamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Param_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Param_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Param_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Param_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.sections == rhs.sections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Param_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Param_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Param_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Param_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Param_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Param_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Param_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Param_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a622953c6a470fc6b967c199f17d8697";
  }

  static const char* value(const ::jarvis_msgs::Param_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa622953c6a470fc6ULL;
  static const uint64_t static_value2 = 0xb967c199f17d8697ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Param";
  }

  static const char* value(const ::jarvis_msgs::Param_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"string sections\n"
;
  }

  static const char* value(const ::jarvis_msgs::Param_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Param_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.sections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Param_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Param_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Param_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "sections: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sections);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_PARAM_H
