// Generated by gencpp from file jarvis_msgs/PlanPath.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_PLANPATH_H
#define JARVIS_MSGS_MESSAGE_PLANPATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct PlanPath_
{
  typedef PlanPath_<ContainerAllocator> Type;

  PlanPath_()
    : stamp()
    , state(0)
    , path()  {
    }
  PlanPath_(const ContainerAllocator& _alloc)
    : stamp()
    , state(0)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int8_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::jarvis_msgs::PlanPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::PlanPath_<ContainerAllocator> const> ConstPtr;

}; // struct PlanPath_

typedef ::jarvis_msgs::PlanPath_<std::allocator<void> > PlanPath;

typedef boost::shared_ptr< ::jarvis_msgs::PlanPath > PlanPathPtr;
typedef boost::shared_ptr< ::jarvis_msgs::PlanPath const> PlanPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::PlanPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::PlanPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::PlanPath_<ContainerAllocator1> & lhs, const ::jarvis_msgs::PlanPath_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.state == rhs.state &&
    lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::PlanPath_<ContainerAllocator1> & lhs, const ::jarvis_msgs::PlanPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::PlanPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::PlanPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::PlanPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::PlanPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::PlanPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::PlanPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::PlanPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7add8d528af57f1231b551bfa8b4a3c9";
  }

  static const char* value(const ::jarvis_msgs::PlanPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7add8d528af57f12ULL;
  static const uint64_t static_value2 = 0x31b551bfa8b4a3c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::PlanPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/PlanPath";
  }

  static const char* value(const ::jarvis_msgs::PlanPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::PlanPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"int8 state\n"
"string path\n"
;
  }

  static const char* value(const ::jarvis_msgs::PlanPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::PlanPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.state);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::PlanPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::PlanPath_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_PLANPATH_H
