// Generated by gencpp from file jarvis_msgs/RecordBagRequest.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_RECORDBAGREQUEST_H
#define JARVIS_MSGS_MESSAGE_RECORDBAGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct RecordBagRequest_
{
  typedef RecordBagRequest_<ContainerAllocator> Type;

  RecordBagRequest_()
    : data(false)
    , name()  {
    }
  RecordBagRequest_(const ContainerAllocator& _alloc)
    : data(false)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RecordBagRequest_

typedef ::jarvis_msgs::RecordBagRequest_<std::allocator<void> > RecordBagRequest;

typedef boost::shared_ptr< ::jarvis_msgs::RecordBagRequest > RecordBagRequestPtr;
typedef boost::shared_ptr< ::jarvis_msgs::RecordBagRequest const> RecordBagRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::RecordBagRequest_<ContainerAllocator1> & lhs, const ::jarvis_msgs::RecordBagRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::RecordBagRequest_<ContainerAllocator1> & lhs, const ::jarvis_msgs::RecordBagRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b182175b0cfa2a77f4a8a407f0d3f68";
  }

  static const char* value(const ::jarvis_msgs::RecordBagRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b182175b0cfa2a7ULL;
  static const uint64_t static_value2 = 0x7f4a8a407f0d3f68ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/RecordBagRequest";
  }

  static const char* value(const ::jarvis_msgs::RecordBagRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool data # start/stop rosbag record service\n"
"string name # map's name\n"
;
  }

  static const char* value(const ::jarvis_msgs::RecordBagRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecordBagRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::RecordBagRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::RecordBagRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_RECORDBAGREQUEST_H
