// Generated by gencpp from file jarvis_msgs/RecordBag.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_RECORDBAG_H
#define JARVIS_MSGS_MESSAGE_RECORDBAG_H

#include <ros/service_traits.h>


#include <jarvis_msgs/RecordBagRequest.h>
#include <jarvis_msgs/RecordBagResponse.h>


namespace jarvis_msgs
{

struct RecordBag
{

typedef RecordBagRequest Request;
typedef RecordBagResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecordBag
} // namespace jarvis_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jarvis_msgs::RecordBag > {
  static const char* value()
  {
    return "62418f0fe8c8d69b531312ba1ed82a56";
  }

  static const char* value(const ::jarvis_msgs::RecordBag&) { return value(); }
};

template<>
struct DataType< ::jarvis_msgs::RecordBag > {
  static const char* value()
  {
    return "jarvis_msgs/RecordBag";
  }

  static const char* value(const ::jarvis_msgs::RecordBag&) { return value(); }
};


// service_traits::MD5Sum< ::jarvis_msgs::RecordBagRequest> should match
// service_traits::MD5Sum< ::jarvis_msgs::RecordBag >
template<>
struct MD5Sum< ::jarvis_msgs::RecordBagRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jarvis_msgs::RecordBag >::value();
  }
  static const char* value(const ::jarvis_msgs::RecordBagRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jarvis_msgs::RecordBagRequest> should match
// service_traits::DataType< ::jarvis_msgs::RecordBag >
template<>
struct DataType< ::jarvis_msgs::RecordBagRequest>
{
  static const char* value()
  {
    return DataType< ::jarvis_msgs::RecordBag >::value();
  }
  static const char* value(const ::jarvis_msgs::RecordBagRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jarvis_msgs::RecordBagResponse> should match
// service_traits::MD5Sum< ::jarvis_msgs::RecordBag >
template<>
struct MD5Sum< ::jarvis_msgs::RecordBagResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jarvis_msgs::RecordBag >::value();
  }
  static const char* value(const ::jarvis_msgs::RecordBagResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jarvis_msgs::RecordBagResponse> should match
// service_traits::DataType< ::jarvis_msgs::RecordBag >
template<>
struct DataType< ::jarvis_msgs::RecordBagResponse>
{
  static const char* value()
  {
    return DataType< ::jarvis_msgs::RecordBag >::value();
  }
  static const char* value(const ::jarvis_msgs::RecordBagResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_RECORDBAG_H
