// Generated by gencpp from file jarvis_msgs/RefPoint.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_REFPOINT_H
#define JARVIS_MSGS_MESSAGE_REFPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct RefPoint_
{
  typedef RefPoint_<ContainerAllocator> Type;

  RefPoint_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , v(0.0)  {
    }
  RefPoint_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , v(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _v_type;
  _v_type v;





  typedef boost::shared_ptr< ::jarvis_msgs::RefPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::RefPoint_<ContainerAllocator> const> ConstPtr;

}; // struct RefPoint_

typedef ::jarvis_msgs::RefPoint_<std::allocator<void> > RefPoint;

typedef boost::shared_ptr< ::jarvis_msgs::RefPoint > RefPointPtr;
typedef boost::shared_ptr< ::jarvis_msgs::RefPoint const> RefPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::RefPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::RefPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::RefPoint_<ContainerAllocator1> & lhs, const ::jarvis_msgs::RefPoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw &&
    lhs.v == rhs.v;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::RefPoint_<ContainerAllocator1> & lhs, const ::jarvis_msgs::RefPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::RefPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::RefPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::RefPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::RefPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::RefPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::RefPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::RefPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d02065475d2208fe262b04f47261a35";
  }

  static const char* value(const ::jarvis_msgs::RefPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d02065475d2208fULL;
  static const uint64_t static_value2 = 0xe262b04f47261a35ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::RefPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/RefPoint";
  }

  static const char* value(const ::jarvis_msgs::RefPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::RefPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RefPoint.msg（ROS 自定义消息，与 C++ 结构体成员一致）\n"
"float64 x        # x坐标（m）\n"
"float64 y        # y坐标（m）\n"
"float64 yaw      # 偏航角（rad）\n"
"float64 v        # 速度（m/s，可选）\n"
"\n"
;
  }

  static const char* value(const ::jarvis_msgs::RefPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::RefPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RefPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::RefPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::RefPoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_REFPOINT_H
