// Generated by gencpp from file jarvis_msgs/RobotStatus.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_ROBOTSTATUS_H
#define JARVIS_MSGS_MESSAGE_ROBOTSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct RobotStatus_
{
  typedef RobotStatus_<ContainerAllocator> Type;

  RobotStatus_()
    : system_status()
    , system_error_code(0)
    , v_set(0)
    , w_set(0.0)
    , odom_v(0.0)
    , odom_w(0.0)
    , odom_theta(0.0)
    , trun_time(0)
    , trun_m(0.0)
    , motor_enable(0)
    , motor_enable_status(0)
    , acc(0.0)
    , dec(0.0)
    , charge(0)
    , EQ(0)
    , bms_voltage(0.0)
    , bms_current(0.0)
    , l_status(0)
    , l_error(0)
    , l_IQ(0.0)
    , l_enc(0)
    , l_enc_set(0)
    , l_rpm(0.0)
    , l_rpm_set(0.0)
    , r_status(0)
    , r_error(0)
    , r_IQ(0.0)
    , r_enc(0)
    , r_enc_set(0)
    , r_rpm(0.0)
    , r_rpm_set(0.0)
    , lift_status(0)
    , lift_IQ(0.0)
    , lift_IO_status(0)
    , rotate_status(0)
    , rotate_IQ(0.0)
    , rotate_IO_status(0)
    , Outputset(0)
    , InputState(0)
    , motorboolestop(0)
    , bumpe_stop(0)
    , hmi_estop(0)
    , motor_error(0)
    , pc_estop(0)
    , pc_enable(0)  {
    }
  RobotStatus_(const ContainerAllocator& _alloc)
    : system_status(_alloc)
    , system_error_code(0)
    , v_set(0)
    , w_set(0.0)
    , odom_v(0.0)
    , odom_w(0.0)
    , odom_theta(0.0)
    , trun_time(0)
    , trun_m(0.0)
    , motor_enable(0)
    , motor_enable_status(0)
    , acc(0.0)
    , dec(0.0)
    , charge(0)
    , EQ(0)
    , bms_voltage(0.0)
    , bms_current(0.0)
    , l_status(0)
    , l_error(0)
    , l_IQ(0.0)
    , l_enc(0)
    , l_enc_set(0)
    , l_rpm(0.0)
    , l_rpm_set(0.0)
    , r_status(0)
    , r_error(0)
    , r_IQ(0.0)
    , r_enc(0)
    , r_enc_set(0)
    , r_rpm(0.0)
    , r_rpm_set(0.0)
    , lift_status(0)
    , lift_IQ(0.0)
    , lift_IO_status(0)
    , rotate_status(0)
    , rotate_IQ(0.0)
    , rotate_IO_status(0)
    , Outputset(0)
    , InputState(0)
    , motorboolestop(0)
    , bumpe_stop(0)
    , hmi_estop(0)
    , motor_error(0)
    , pc_estop(0)
    , pc_enable(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _system_status_type;
  _system_status_type system_status;

   typedef uint16_t _system_error_code_type;
  _system_error_code_type system_error_code;

   typedef int32_t _v_set_type;
  _v_set_type v_set;

   typedef float _w_set_type;
  _w_set_type w_set;

   typedef float _odom_v_type;
  _odom_v_type odom_v;

   typedef float _odom_w_type;
  _odom_w_type odom_w;

   typedef float _odom_theta_type;
  _odom_theta_type odom_theta;

   typedef int32_t _trun_time_type;
  _trun_time_type trun_time;

   typedef float _trun_m_type;
  _trun_m_type trun_m;

   typedef uint8_t _motor_enable_type;
  _motor_enable_type motor_enable;

   typedef uint8_t _motor_enable_status_type;
  _motor_enable_status_type motor_enable_status;

   typedef float _acc_type;
  _acc_type acc;

   typedef float _dec_type;
  _dec_type dec;

   typedef uint8_t _charge_type;
  _charge_type charge;

   typedef uint8_t _EQ_type;
  _EQ_type EQ;

   typedef float _bms_voltage_type;
  _bms_voltage_type bms_voltage;

   typedef float _bms_current_type;
  _bms_current_type bms_current;

   typedef uint16_t _l_status_type;
  _l_status_type l_status;

   typedef uint16_t _l_error_type;
  _l_error_type l_error;

   typedef float _l_IQ_type;
  _l_IQ_type l_IQ;

   typedef int32_t _l_enc_type;
  _l_enc_type l_enc;

   typedef int32_t _l_enc_set_type;
  _l_enc_set_type l_enc_set;

   typedef float _l_rpm_type;
  _l_rpm_type l_rpm;

   typedef float _l_rpm_set_type;
  _l_rpm_set_type l_rpm_set;

   typedef uint16_t _r_status_type;
  _r_status_type r_status;

   typedef uint16_t _r_error_type;
  _r_error_type r_error;

   typedef float _r_IQ_type;
  _r_IQ_type r_IQ;

   typedef int32_t _r_enc_type;
  _r_enc_type r_enc;

   typedef int32_t _r_enc_set_type;
  _r_enc_set_type r_enc_set;

   typedef float _r_rpm_type;
  _r_rpm_type r_rpm;

   typedef float _r_rpm_set_type;
  _r_rpm_set_type r_rpm_set;

   typedef uint16_t _lift_status_type;
  _lift_status_type lift_status;

   typedef float _lift_IQ_type;
  _lift_IQ_type lift_IQ;

   typedef uint8_t _lift_IO_status_type;
  _lift_IO_status_type lift_IO_status;

   typedef uint16_t _rotate_status_type;
  _rotate_status_type rotate_status;

   typedef float _rotate_IQ_type;
  _rotate_IQ_type rotate_IQ;

   typedef uint8_t _rotate_IO_status_type;
  _rotate_IO_status_type rotate_IO_status;

   typedef int32_t _Outputset_type;
  _Outputset_type Outputset;

   typedef int32_t _InputState_type;
  _InputState_type InputState;

   typedef uint8_t _motorboolestop_type;
  _motorboolestop_type motorboolestop;

   typedef uint8_t _bumpe_stop_type;
  _bumpe_stop_type bumpe_stop;

   typedef uint8_t _hmi_estop_type;
  _hmi_estop_type hmi_estop;

   typedef uint8_t _motor_error_type;
  _motor_error_type motor_error;

   typedef uint8_t _pc_estop_type;
  _pc_estop_type pc_estop;

   typedef uint8_t _pc_enable_type;
  _pc_enable_type pc_enable;





  typedef boost::shared_ptr< ::jarvis_msgs::RobotStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::RobotStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatus_

typedef ::jarvis_msgs::RobotStatus_<std::allocator<void> > RobotStatus;

typedef boost::shared_ptr< ::jarvis_msgs::RobotStatus > RobotStatusPtr;
typedef boost::shared_ptr< ::jarvis_msgs::RobotStatus const> RobotStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::RobotStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::RobotStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::RobotStatus_<ContainerAllocator1> & lhs, const ::jarvis_msgs::RobotStatus_<ContainerAllocator2> & rhs)
{
  return lhs.system_status == rhs.system_status &&
    lhs.system_error_code == rhs.system_error_code &&
    lhs.v_set == rhs.v_set &&
    lhs.w_set == rhs.w_set &&
    lhs.odom_v == rhs.odom_v &&
    lhs.odom_w == rhs.odom_w &&
    lhs.odom_theta == rhs.odom_theta &&
    lhs.trun_time == rhs.trun_time &&
    lhs.trun_m == rhs.trun_m &&
    lhs.motor_enable == rhs.motor_enable &&
    lhs.motor_enable_status == rhs.motor_enable_status &&
    lhs.acc == rhs.acc &&
    lhs.dec == rhs.dec &&
    lhs.charge == rhs.charge &&
    lhs.EQ == rhs.EQ &&
    lhs.bms_voltage == rhs.bms_voltage &&
    lhs.bms_current == rhs.bms_current &&
    lhs.l_status == rhs.l_status &&
    lhs.l_error == rhs.l_error &&
    lhs.l_IQ == rhs.l_IQ &&
    lhs.l_enc == rhs.l_enc &&
    lhs.l_enc_set == rhs.l_enc_set &&
    lhs.l_rpm == rhs.l_rpm &&
    lhs.l_rpm_set == rhs.l_rpm_set &&
    lhs.r_status == rhs.r_status &&
    lhs.r_error == rhs.r_error &&
    lhs.r_IQ == rhs.r_IQ &&
    lhs.r_enc == rhs.r_enc &&
    lhs.r_enc_set == rhs.r_enc_set &&
    lhs.r_rpm == rhs.r_rpm &&
    lhs.r_rpm_set == rhs.r_rpm_set &&
    lhs.lift_status == rhs.lift_status &&
    lhs.lift_IQ == rhs.lift_IQ &&
    lhs.lift_IO_status == rhs.lift_IO_status &&
    lhs.rotate_status == rhs.rotate_status &&
    lhs.rotate_IQ == rhs.rotate_IQ &&
    lhs.rotate_IO_status == rhs.rotate_IO_status &&
    lhs.Outputset == rhs.Outputset &&
    lhs.InputState == rhs.InputState &&
    lhs.motorboolestop == rhs.motorboolestop &&
    lhs.bumpe_stop == rhs.bumpe_stop &&
    lhs.hmi_estop == rhs.hmi_estop &&
    lhs.motor_error == rhs.motor_error &&
    lhs.pc_estop == rhs.pc_estop &&
    lhs.pc_enable == rhs.pc_enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::RobotStatus_<ContainerAllocator1> & lhs, const ::jarvis_msgs::RobotStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ea91f3f23827c0e9a7c9a95b6a3017b";
  }

  static const char* value(const ::jarvis_msgs::RobotStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ea91f3f23827c0eULL;
  static const uint64_t static_value2 = 0x9a7c9a95b6a3017bULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/RobotStatus";
  }

  static const char* value(const ::jarvis_msgs::RobotStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string system_status\n"
"uint16 system_error_code\n"
"int32 v_set\n"
"float32 w_set\n"
"float32 odom_v\n"
"float32 odom_w\n"
"float32 odom_theta\n"
"int32 trun_time\n"
"float32 trun_m\n"
"uint8 motor_enable\n"
"uint8 motor_enable_status\n"
"float32  acc\n"
"float32  dec\n"
"uint8 charge\n"
"uint8 EQ\n"
"float32 bms_voltage\n"
"float32 bms_current\n"
"uint16 l_status\n"
"uint16 l_error\n"
"float32 l_IQ\n"
"int32 l_enc\n"
"int32 l_enc_set\n"
"float32  l_rpm\n"
"float32 l_rpm_set\n"
"uint16 r_status\n"
"uint16 r_error\n"
"float32 r_IQ\n"
"int32 r_enc\n"
"int32 r_enc_set\n"
"float32 r_rpm\n"
"float32 r_rpm_set\n"
"uint16 lift_status\n"
"float32 lift_IQ\n"
"uint8 lift_IO_status\n"
"uint16 rotate_status\n"
"float32 rotate_IQ\n"
"uint8 rotate_IO_status\n"
"int32 Outputset\n"
"int32 InputState\n"
"uint8 motorboolestop\n"
"uint8 bumpe_stop\n"
"uint8 hmi_estop\n"
"uint8 motor_error\n"
"uint8 pc_estop\n"
"uint8 pc_enable\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::jarvis_msgs::RobotStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::RobotStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.system_status);
      stream.next(m.system_error_code);
      stream.next(m.v_set);
      stream.next(m.w_set);
      stream.next(m.odom_v);
      stream.next(m.odom_w);
      stream.next(m.odom_theta);
      stream.next(m.trun_time);
      stream.next(m.trun_m);
      stream.next(m.motor_enable);
      stream.next(m.motor_enable_status);
      stream.next(m.acc);
      stream.next(m.dec);
      stream.next(m.charge);
      stream.next(m.EQ);
      stream.next(m.bms_voltage);
      stream.next(m.bms_current);
      stream.next(m.l_status);
      stream.next(m.l_error);
      stream.next(m.l_IQ);
      stream.next(m.l_enc);
      stream.next(m.l_enc_set);
      stream.next(m.l_rpm);
      stream.next(m.l_rpm_set);
      stream.next(m.r_status);
      stream.next(m.r_error);
      stream.next(m.r_IQ);
      stream.next(m.r_enc);
      stream.next(m.r_enc_set);
      stream.next(m.r_rpm);
      stream.next(m.r_rpm_set);
      stream.next(m.lift_status);
      stream.next(m.lift_IQ);
      stream.next(m.lift_IO_status);
      stream.next(m.rotate_status);
      stream.next(m.rotate_IQ);
      stream.next(m.rotate_IO_status);
      stream.next(m.Outputset);
      stream.next(m.InputState);
      stream.next(m.motorboolestop);
      stream.next(m.bumpe_stop);
      stream.next(m.hmi_estop);
      stream.next(m.motor_error);
      stream.next(m.pc_estop);
      stream.next(m.pc_enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::RobotStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::RobotStatus_<ContainerAllocator>& v)
  {
    s << indent << "system_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.system_status);
    s << indent << "system_error_code: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.system_error_code);
    s << indent << "v_set: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v_set);
    s << indent << "w_set: ";
    Printer<float>::stream(s, indent + "  ", v.w_set);
    s << indent << "odom_v: ";
    Printer<float>::stream(s, indent + "  ", v.odom_v);
    s << indent << "odom_w: ";
    Printer<float>::stream(s, indent + "  ", v.odom_w);
    s << indent << "odom_theta: ";
    Printer<float>::stream(s, indent + "  ", v.odom_theta);
    s << indent << "trun_time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.trun_time);
    s << indent << "trun_m: ";
    Printer<float>::stream(s, indent + "  ", v.trun_m);
    s << indent << "motor_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor_enable);
    s << indent << "motor_enable_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor_enable_status);
    s << indent << "acc: ";
    Printer<float>::stream(s, indent + "  ", v.acc);
    s << indent << "dec: ";
    Printer<float>::stream(s, indent + "  ", v.dec);
    s << indent << "charge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.charge);
    s << indent << "EQ: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.EQ);
    s << indent << "bms_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.bms_voltage);
    s << indent << "bms_current: ";
    Printer<float>::stream(s, indent + "  ", v.bms_current);
    s << indent << "l_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.l_status);
    s << indent << "l_error: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.l_error);
    s << indent << "l_IQ: ";
    Printer<float>::stream(s, indent + "  ", v.l_IQ);
    s << indent << "l_enc: ";
    Printer<int32_t>::stream(s, indent + "  ", v.l_enc);
    s << indent << "l_enc_set: ";
    Printer<int32_t>::stream(s, indent + "  ", v.l_enc_set);
    s << indent << "l_rpm: ";
    Printer<float>::stream(s, indent + "  ", v.l_rpm);
    s << indent << "l_rpm_set: ";
    Printer<float>::stream(s, indent + "  ", v.l_rpm_set);
    s << indent << "r_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.r_status);
    s << indent << "r_error: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.r_error);
    s << indent << "r_IQ: ";
    Printer<float>::stream(s, indent + "  ", v.r_IQ);
    s << indent << "r_enc: ";
    Printer<int32_t>::stream(s, indent + "  ", v.r_enc);
    s << indent << "r_enc_set: ";
    Printer<int32_t>::stream(s, indent + "  ", v.r_enc_set);
    s << indent << "r_rpm: ";
    Printer<float>::stream(s, indent + "  ", v.r_rpm);
    s << indent << "r_rpm_set: ";
    Printer<float>::stream(s, indent + "  ", v.r_rpm_set);
    s << indent << "lift_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.lift_status);
    s << indent << "lift_IQ: ";
    Printer<float>::stream(s, indent + "  ", v.lift_IQ);
    s << indent << "lift_IO_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lift_IO_status);
    s << indent << "rotate_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.rotate_status);
    s << indent << "rotate_IQ: ";
    Printer<float>::stream(s, indent + "  ", v.rotate_IQ);
    s << indent << "rotate_IO_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rotate_IO_status);
    s << indent << "Outputset: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Outputset);
    s << indent << "InputState: ";
    Printer<int32_t>::stream(s, indent + "  ", v.InputState);
    s << indent << "motorboolestop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motorboolestop);
    s << indent << "bumpe_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bumpe_stop);
    s << indent << "hmi_estop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hmi_estop);
    s << indent << "motor_error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor_error);
    s << indent << "pc_estop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pc_estop);
    s << indent << "pc_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pc_enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_ROBOTSTATUS_H
