// Generated by gencpp from file jarvis_msgs/RotateRes.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_ROTATERES_H
#define JARVIS_MSGS_MESSAGE_ROTATERES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct RotateRes_
{
  typedef RotateRes_<ContainerAllocator> Type;

  RotateRes_()
    : w(0.0)
    , angle(0.0)  {
    }
  RotateRes_(const ContainerAllocator& _alloc)
    : w(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _w_type;
  _w_type w;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::jarvis_msgs::RotateRes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::RotateRes_<ContainerAllocator> const> ConstPtr;

}; // struct RotateRes_

typedef ::jarvis_msgs::RotateRes_<std::allocator<void> > RotateRes;

typedef boost::shared_ptr< ::jarvis_msgs::RotateRes > RotateResPtr;
typedef boost::shared_ptr< ::jarvis_msgs::RotateRes const> RotateResConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::RotateRes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::RotateRes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::RotateRes_<ContainerAllocator1> & lhs, const ::jarvis_msgs::RotateRes_<ContainerAllocator2> & rhs)
{
  return lhs.w == rhs.w &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::RotateRes_<ContainerAllocator1> & lhs, const ::jarvis_msgs::RotateRes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::RotateRes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::RotateRes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::RotateRes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::RotateRes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::RotateRes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::RotateRes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::RotateRes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edc04dd9a544faa5e2f2b13b41b03a08";
  }

  static const char* value(const ::jarvis_msgs::RotateRes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xedc04dd9a544faa5ULL;
  static const uint64_t static_value2 = 0xe2f2b13b41b03a08ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::RotateRes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/RotateRes";
  }

  static const char* value(const ::jarvis_msgs::RotateRes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::RotateRes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 w\n"
"float32 angle\n"
;
  }

  static const char* value(const ::jarvis_msgs::RotateRes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::RotateRes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.w);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RotateRes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::RotateRes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::RotateRes_<ContainerAllocator>& v)
  {
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_ROTATERES_H
