// Generated by gencpp from file jarvis_msgs/Rotate.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_ROTATE_H
#define JARVIS_MSGS_MESSAGE_ROTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Rotate_
{
  typedef Rotate_<ContainerAllocator> Type;

  Rotate_()
    : w(0.0)  {
    }
  Rotate_(const ContainerAllocator& _alloc)
    : w(0.0)  {
  (void)_alloc;
    }



   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::jarvis_msgs::Rotate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Rotate_<ContainerAllocator> const> ConstPtr;

}; // struct Rotate_

typedef ::jarvis_msgs::Rotate_<std::allocator<void> > Rotate;

typedef boost::shared_ptr< ::jarvis_msgs::Rotate > RotatePtr;
typedef boost::shared_ptr< ::jarvis_msgs::Rotate const> RotateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Rotate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Rotate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Rotate_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Rotate_<ContainerAllocator2> & rhs)
{
  return lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Rotate_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Rotate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Rotate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Rotate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Rotate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Rotate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Rotate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Rotate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2998be8e50fd94f088023945b6a432a2";
  }

  static const char* value(const ::jarvis_msgs::Rotate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2998be8e50fd94f0ULL;
  static const uint64_t static_value2 = 0x88023945b6a432a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Rotate";
  }

  static const char* value(const ::jarvis_msgs::Rotate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 w\n"
;
  }

  static const char* value(const ::jarvis_msgs::Rotate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Rotate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rotate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Rotate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Rotate_<ContainerAllocator>& v)
  {
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_ROTATE_H
