// Generated by gencpp from file jarvis_msgs/Sonar.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_SONAR_H
#define JARVIS_MSGS_MESSAGE_SONAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Sonar_
{
  typedef Sonar_<ContainerAllocator> Type;

  Sonar_()
    : data()  {
      data.assign(0);
  }
  Sonar_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef boost::array<int8_t, 8>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::jarvis_msgs::Sonar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Sonar_<ContainerAllocator> const> ConstPtr;

}; // struct Sonar_

typedef ::jarvis_msgs::Sonar_<std::allocator<void> > Sonar;

typedef boost::shared_ptr< ::jarvis_msgs::Sonar > SonarPtr;
typedef boost::shared_ptr< ::jarvis_msgs::Sonar const> SonarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Sonar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Sonar_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Sonar_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Sonar_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Sonar_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Sonar_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Sonar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Sonar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Sonar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Sonar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Sonar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Sonar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Sonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "706749c5d2cef0d461ec58e65a6dbfb6";
  }

  static const char* value(const ::jarvis_msgs::Sonar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x706749c5d2cef0d4ULL;
  static const uint64_t static_value2 = 0x61ec58e65a6dbfb6ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Sonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Sonar";
  }

  static const char* value(const ::jarvis_msgs::Sonar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Sonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[8] data\n"
"\n"
;
  }

  static const char* value(const ::jarvis_msgs::Sonar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Sonar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sonar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Sonar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Sonar_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_SONAR_H
