// Generated by gencpp from file jarvis_msgs/Vel.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_VEL_H
#define JARVIS_MSGS_MESSAGE_VEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct Vel_
{
  typedef Vel_<ContainerAllocator> Type;

  Vel_()
    : stamp(0)
    , v(0.0)
    , w(0.0)  {
    }
  Vel_(const ContainerAllocator& _alloc)
    : stamp(0)
    , v(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _stamp_type;
  _stamp_type stamp;

   typedef float _v_type;
  _v_type v;

   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::jarvis_msgs::Vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::Vel_<ContainerAllocator> const> ConstPtr;

}; // struct Vel_

typedef ::jarvis_msgs::Vel_<std::allocator<void> > Vel;

typedef boost::shared_ptr< ::jarvis_msgs::Vel > VelPtr;
typedef boost::shared_ptr< ::jarvis_msgs::Vel const> VelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::Vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::Vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::Vel_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Vel_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.v == rhs.v &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::Vel_<ContainerAllocator1> & lhs, const ::jarvis_msgs::Vel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::Vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::Vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::Vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b82d3242b01158a4e3712a5e4704366";
  }

  static const char* value(const ::jarvis_msgs::Vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b82d3242b01158aULL;
  static const uint64_t static_value2 = 0x4e3712a5e4704366ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/Vel";
  }

  static const char* value(const ::jarvis_msgs::Vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 stamp\n"
"float32 v\n"
"float32 w\n"
;
  }

  static const char* value(const ::jarvis_msgs::Vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::Vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.v);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::Vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::Vel_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.stamp);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_VEL_H
