// Generated by gencpp from file jarvis_msgs/VelSteer.msg
// DO NOT EDIT!


#ifndef JARVIS_MSGS_MESSAGE_VELSTEER_H
#define JARVIS_MSGS_MESSAGE_VELSTEER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jarvis_msgs
{
template <class ContainerAllocator>
struct VelSteer_
{
  typedef VelSteer_<ContainerAllocator> Type;

  VelSteer_()
    : stamp(0)
    , vx(0.0)
    , vy(0.0)
    , w(0.0)  {
    }
  VelSteer_(const ContainerAllocator& _alloc)
    : stamp(0)
    , vx(0.0)
    , vy(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _stamp_type;
  _stamp_type stamp;

   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::jarvis_msgs::VelSteer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jarvis_msgs::VelSteer_<ContainerAllocator> const> ConstPtr;

}; // struct VelSteer_

typedef ::jarvis_msgs::VelSteer_<std::allocator<void> > VelSteer;

typedef boost::shared_ptr< ::jarvis_msgs::VelSteer > VelSteerPtr;
typedef boost::shared_ptr< ::jarvis_msgs::VelSteer const> VelSteerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jarvis_msgs::VelSteer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jarvis_msgs::VelSteer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jarvis_msgs::VelSteer_<ContainerAllocator1> & lhs, const ::jarvis_msgs::VelSteer_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jarvis_msgs::VelSteer_<ContainerAllocator1> & lhs, const ::jarvis_msgs::VelSteer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jarvis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::VelSteer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jarvis_msgs::VelSteer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::VelSteer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jarvis_msgs::VelSteer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::VelSteer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jarvis_msgs::VelSteer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jarvis_msgs::VelSteer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1883033053ff8d3bccdc0b24f4765201";
  }

  static const char* value(const ::jarvis_msgs::VelSteer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1883033053ff8d3bULL;
  static const uint64_t static_value2 = 0xccdc0b24f4765201ULL;
};

template<class ContainerAllocator>
struct DataType< ::jarvis_msgs::VelSteer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jarvis_msgs/VelSteer";
  }

  static const char* value(const ::jarvis_msgs::VelSteer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jarvis_msgs::VelSteer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 stamp\n"
"float32 vx\n"
"float32 vy\n"
"float32 w\n"
;
  }

  static const char* value(const ::jarvis_msgs::VelSteer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jarvis_msgs::VelSteer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelSteer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jarvis_msgs::VelSteer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jarvis_msgs::VelSteer_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.stamp);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARVIS_MSGS_MESSAGE_VELSTEER_H
